spring:
  application:
    name: service-center
  boot:
    admin:
      client:
        #springboot admin client连接 spring boot admin server 端点地址
        url: http://localhost:18099
        instance:
          #默认使用的是主机名注册，改为使用ip注册
          prefer-ip: true
        username: admin
        password: 123456
### 监控中心配置, 允许监控所有接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: false
    hostname: eureka-server2 #eureka实例名
  server:
    #eureka server刷新readCacheMap的时间，
    #注意，client读取的是readCacheMap，
    #这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    #默认30s
    response-cache-update-interval-ms: 30000
    #eureka server缓存readWriteCacheMap失效时间，
    #这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    #过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    #由于启用了evict其实就用不太上改这个配置了
    #默认180s
    response-cache-auto-expiration-in-seconds: 180
    #启用主动失效，并且每次主动失效检测间隔为30s
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: false #自我保护模式（为打开）
    lease-renewal-interval-in-seconds: 5 #表示eureka client发送心跳给server端的频率 
    lease-expiration-duration-in-seconds: 7 #发呆时间，即服务续约到期时间
  client:
    serviceUrl:
      #集群版，设置与Eureka Server交互的地址
      defaultZone: http://localhost:8761/eureka/
      #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，
logging:
  config: classpath:logback-boot.xml