spring:
  #profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml